name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Typecheck files
        run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: pnpm run test --maxWorkers=2 --coverage

  build-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: pnpm run build

  example-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Validate Expo config
        run: pnpm run example:build
